### DISCUSSION TITLE
Is it possible to use lists in the Evaluation Context?

### DISCUSSION THREAD

**Discussion by jmkelm08** [thomaspoignant/go-feature-flag#1185] [Q&A] [answered]
I would like to be able to target users based on group membership. In my scenario, a user can be a member of multiple groups, so I put `"groups": ["Group1", "Group2"]` in the Evaluation Context. I attempted to target the user with `query: '"Group1" in groups'`, but it seems the right side of the `in` operator must be a constant expression (for example, `query: 'group in ["Group1", "Group2"]'` does work assuming `"group": "Group1"` has been added to the Evaluation Context).

Note: I tested using https://gofeatureflag.org/editor with the configurations shown below

Evaluation Context
```
{
  "key": "aae1cb41-c3cb-4753-a117-031ddc958e81",
  "custom": {
    "anonymous": true,
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@gofeatureflag.org",
    "company": "GO Feature Flag",
    "groups": ["Group1", "Group2"],
    "group": "Group1"
  }
}
```

Flag Definition 1 (does not work)
```
my-first-flag:
  variations:
    Variation_1: true
    Variation_2: false
  targeting:
    - name: Rule 1
      query: '"Group1" in groups'
      variation: Variation_1
  defaultRule:
    variation: Variation_2
```

Flag Definition 2 (does work)
```
my-first-flag:
  variations:
    Variation_1: true
    Variation_2: false
  targeting:
    - name: Rule 1
      query: 'group in ["Group1", "Group2"]'
      variation: Variation_1
  defaultRule:
    variation: Variation_2
```

What is the best way to accomplish this type of targeting logic?
