### DISCUSSION TITLE
K8S Relay proxy config templating

### DISCUSSION THREAD

**Discussion by tomflenner** [thomaspoignant/go-feature-flag#1820] [Q&A] [answered]
Hi 👋🏻 !

According to the documentation, the `relayproxy.config` accept `tpl/obj` (see [here](https://github.com/thomaspoignant/go-feature-flag/tree/main/cmd/relayproxy/helm-charts/relay-proxy#:~:text=relayproxy.config-,tpl/object,-relayproxy.config%3A%20%7C%0A%20%20listen)).

Unless I'm mistaken, that doesn't seems to be the case (see config use [here](https://github.com/thomaspoignant/go-feature-flag/blob/55a85c964ec6177cad39011a61a6d6e547a19ae6/cmd/relayproxy/helm-charts/relay-proxy/templates/configmap.yaml#L11)).

I try to use Kubernetes retriever and dynamically set the namespace of the configmap with the current helm release as following :
```
    config: |
      retrievers:
      - kind: configmap
        namespace: {{ .Release.Namespace }}
        configmap: feature-flags
        key: flags
      fileFormat: json
      pollingInterval: 5000
      startWithRetrieverError: true
``` 

But the output template is still `namespace: {{ .Release.Namespace }}`

If you have any suggestions it would be appreciated 🙏🏻 

Thanks in advance !
