### DISCUSSION TITLE
Grouping of feature flags

### DISCUSSION THREAD

**Discussion by NicklasWallgren** [thomaspoignant/go-feature-flag#3243] [Q&A] [answered]
Is it possible to group feature flags by application or separate them in a way that the `allFlags` endpoint only returns flags relevant to a specific application, without having to run multiple instances?

Example;

```yaml
# First flag associated with an application called app1
app1:first-flag:
  variations: # All possible return value for your feature flag
    A: false
    B: true
  targeting:
    - query: application eq "app1"

# Second flag associated with an application called app2
app2:second-flag:
  variations:
    A: "valueA"
    B: "valueB"
    defaultValue: "a default value"
  targeting:
    - query: application eq "app2"
```
