### ISSUE TITLE
(feature) automatic progressive rollout

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#101]
# Requirements
Be able to do a progressive rollout of a flag.
We need a way of automatically increase the percentage of users in the flag during the time.

What we want is to be able to set an **initial percentage** and a **start date**, and also a **complete rollout date** and **percentage**.
During between these 2 dates, the percentage will increase smoothly until reaching the complete rollout percentage.

**Comment by thomaspoignant** [comment]
If we have a rollout strategy configured, we ignore the field `percentage` because the rollout strategy is more important than the field.

The format of the rollout strategy should looks like :
```yaml
test-flag:
  // ...
  rollout:
    progressive:
      percentage:
        initial: 10
        end: 80
      releaseRamp:
        start: 2021-03-20T00:00:00.10-05:00
        end: 2021-04-20T00:00:00.10-05:00
```

In that example
- before the `releaseRamp.start` date the percentage of the flag served will be 10%.
- between `releaseRamp.start` and `releaseRamp.end` we will have a progressive rollout between **10%** and **80%**.
- after `releaseRamp.end` we will use the percentage **80%**.

`rollout.progressive.percentage` is not mandatory, if no set `initial == 0` and `end == 100`.
`rollout.progressive.releaseRamp` is mandatory, if no set we will not use the rollout strategy.
