### ISSUE TITLE
(feature) Scheduling rollout strategy

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#111]
# Requirements
Scheduling introduces the ability for users to plan and pre-define changes to their flags and segments for future points in time. While this sounds deceptively straightforward, it unlocks the potential for users to create complex release strategies by scheduling the incremental steps in advance.

For example, you may want to turn a feature ON for internal testing tomorrow and then enable it for your ‘beta’ user segment four days later. Finally, a week later, you want to start rolling it out from 0% to 100% of your user base. Now, you can define this workflow using flag scheduling and be assured that all the steps will take effect at the specified dates and times.

```yaml
test-flag:
  true: true
  false: false
  default: false
  rollout:
    scheduled:
      steps:
        - date: 2021-04-10T00:00:00.10-05:00
          rule: internal eq true
          percentage: 100
        
        - date: 2021-04-14T00:00:00.10-05:00
          rule: internal eq true OR beta eq true
          percentage: 100

        - date: 2021-05-21T00:00:00.10-05:00
          rule: "" // no restriction on who is affected by the flag
          percentage: 100
```
