### ISSUE TITLE
Experimentation is a rollout strategy

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#112]
# Motivation
Since `experimentation` is a type of rollout, we should change the place used to configure it.

# Requirements
Before we had this type of configuration for the experimentation.
```yaml
experimentation-flag:
  percentage: 50
  true: "B"
  false: "A"
  default: "A"
  experimentation:
    startDate: 2021-03-20T00:00:00.10-05:00
    endDate: 2021-03-21T00:00:00.10-05:00
```

Now we want something like:
```yaml
experimentation-flag:
  percentage: 50
  true: "B"
  false: "A"
  default: "A"
  rollout:
    experimentation:
      start: 2021-03-20T00:00:00.10-05:00
      end: 2021-03-21T00:00:00.10-05:00
```
