### ISSUE TITLE
(bug) Context int values marshall as float with in operator

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1338]
### Observed behavior

As reported in this [slack thread](https://gophers.slack.com/archives/C029TH8KDFG/p1701997487031169), with a targeting 
```json
{
        "name": "Rule 1",
        "query": "office_id in [1,2,3]",
        "variation": "allow"
}
```

And this context:
```json
{ 
   "key": "aae1cb41-c3cb-4753-a117-031ddc958e81", 
   "custom":
   { 
       "office_id": 1
   }
}
```

### Expected Behavior

We expect the rule to match, but it does not.

The reason is that the unmarshaling of the context is setting the value of the context as `float64` while it is an `int64` in the targeting.

### Steps to reproduce

Create a flag that looks like:
```yaml
my-first-flag:
  variations:
    allow: true
    block: false
  targeting:
    - query: office_id in [1,2,3]
      variation: allow
  defaultRule:
    variation: block
```

Call the relay-proxy API with this cURL command:
```shell
curl -X 'POST' \
  'http://localhost:1031/v1/feature/my-first-flag/eval' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "defaultValue": "string",
  "evaluationContext": {
    "custom": {
      "office_id": 1
    },
    "key": "08b5ffb7-7109-42f4-a6f2-b85560fbd20f"
  }
}'
```
