### ISSUE TITLE
(question) What is the difference between using go-feature-flag to implement feature switches and using a configuration center like consul config to implement feature switches? Are there any advantages?

### ISSUE THREAD

**Issue by oomgomgxx** [thomaspoignant/go-feature-flag#1428]
### Your question

What is the difference between using go-feature-flag to implement feature switches and using a configuration center like consul config to implement feature switches? Are there any advantages?

**Comment by thomaspoignant** [comment]
Hey @oomgomgxx, thanks for your question.

Let me sum up the differences between a system like Hashicorp Consul and a feature flag solution like GO Feature Flag.
A system like Consul is a heavy tool that is able to do much more than remote configuration, it is also able to do 
- Service Discovery and Mesh Networking
- Health Checking
- Dynamic App Configuration
- API Gateway
- ....
I am not an expert in Consul, but it seems a lot to put in place only for a remote configuration system.

When it comes to feature flagging one of the main benefits is that it is rollout aware, meaning that you can control how you rollout a change in the configuration, you can apply targeting rules when changing a configuration value, allowing you to smoothly or gradually deploy your new configuration.

Let's say you have a flag for the background colour of your website (_silly example but it will help to understand)_, with feature flagging, you can decide that only a portion of your audience will see the new colour, which will help to define who sees what with in a more fine-grained way.

In GO Feature Flag it can look like this:
```yaml
background-color:
  variations:
    old-version: "#fff"
    new-version: "#333"
    premium-color: "#666"
  targeting:
    - name: premium-customer-color-rule
      query: tier eq "premium_customer"
      variation: premium-color
  defaultRule:
    percentage:
      old-version: 90
      new-version: 10
```

In this example:
- premium customer will have the background `#666`.
- 10% of the rest will see `#333`
- 90% of the rest will see `#fff`
