### ISSUE TITLE
(bug) [relay-proxy] Override configuration via env variables in `retrievers` does not work

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1841]
### Observed behaviour

When running the relayproxy it is possible to override the configuration file using environment variables.
If the configuration to override is inside an array it is not possible to override it.

This is particularly true when dealing with secrets as mentioned in #1822.

With the current implementation of `koanf` this is not working well, we should consider following what is proposed in this issue https://github.com/knadh/koanf/issues/74.

### Expected Behavior

We want to be able to override a property from the key retrievers with an environment variable.

Something like 
```shell 
export RETRIEVERS_0_HEADERS_AUTHORIZATION=Bearer xxx
```

**Comment by luanxuechao** [comment]
Hi @thomaspoignant , I try to fix it, but I've found a bug in local, when I set yaml in the local:
```
listen: 1031
pollingInterval: 1000
startWithRetrieverError: false
retriever:
  kind: http
  url: https://raw.githubusercontent.com/thomaspoignant/go-feature-flag/main/examples/retriever_file/flags.goff.yaml
retrievers:
   - kind: file
     path: examples/retriever_file/flags.goff.yaml
  - kind: file
    path: examples/retriever_file/flags.goff.yaml

exporter:
  kind: log
enableSwagger: true
authorizedKeys:
  evaluation:
    - apikey1 # owner: userID1
    - apikey2 # owner: userID2
  admin:
    - apikey3
```
the `retrievers` of config can't load from the yaml file.

**Comment by thomaspoignant** [comment]
@luanxuechao from your example I see an indentation issue in your file on the providers.
Can you try this one instead?

```yaml
listen: 1031
pollingInterval: 1000
startWithRetrieverError: false
retriever:
  kind: http
  url: https://raw.githubusercontent.com/thomaspoignant/go-feature-flag/main/examples/retriever_file/flags.goff.yaml
retrievers:
  - kind: file
    path: examples/retriever_file/flags.goff.yaml
  - kind: file
    path: examples/retriever_file/flags.goff.yaml

exporter:
  kind: log
enableSwagger: true
authorizedKeys:
  evaluation:
    - apikey1 # owner: userID1
    - apikey2 # owner: userID2
  admin:
    - apikey3
  ```

Can you double check if this is
