### ISSUE TITLE
(feature) Integration with Datadog RUM

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1877]
### Requirements

Datadog is now supporting RUM integration for feature flags (https://docs.datadoghq.com/real_user_monitoring/guide/setup-feature-flag-data-collection/?tab=browser).

It will be great to be able to integrate GO Feature Flag with Datadog.
This will probably be through an OpenFeature Hook.

**Comment by mbezhanov** [comment]
Hello there!

To better understand, are you looking into adding this as an extra initialization option in the JavaScript / TypeScript client provider, or did you have something else in mind?

e.g. something like:
```js
const goFeatureFlagWebProvider = new GoFeatureFlagWebProvider({
  endpoint: endpoint,
  listener: (key, value) => {
     datadogRum.addFeatureFlagEvaluation(key, value);
  },
}, logger);
```

**Comment by thomaspoignant** [comment]
Hello @mbezhanov,
Yes, something like that could work.
I haven't looked at it in detail yet, but this sounds like an elegant solution.

**Comment by mbezhanov** [comment]
I'll give it a shot.

**Comment by mbezhanov** [comment]
Just want to make sure I'm on the right track here. Consider the following potential changes made to the `go-feature-flag-web-provider.ts` file in the `open-telemetry/js-sdk-contrib` repo: https://github.com/mbezhanov/js-sdk-contrib/commit/9308bff9d37ef187f0d3496b6d9e01bf0e9542cb

This allows us to initialize the provider in the following way:

```js
const goFeatureFlagWebProvider = new GoFeatureFlagWebProvider({
    endpoint,
    listener: (key, value) => {
      datadogRum.addFeatureFlagEvaluation(key, value)
    }
  }, logger);
```

Then, if we assume we have the following flags defined in the relay proxy:

```yaml
some-boolean-flag:
  variations:
    A: true
    B: false
  targeting:
    - query: ff eq true
      percentage:
        A: 50
        B: 50
  defaultRule:
    variation: A
some-numeric-flag:
  variations:
    A: 3
    B: 5
    C: 7
  targeting:
    - query: ff eq true
      percentage:
        A: 30
        B: 30
        C: 40
  defaultRule:
    variation: A
some-string-flag:
  variations:
    A: "foo"
    B: "bar"
    C: "baz"
  targeting:
    - query: ff eq true
      percentage:
        A: 30
        B: 30
        C: 40
  defaultRule:
    variation: A
```

And we perform similar evaluations in our code:

```js
if (client.getBooleanValue('some-boolean-flag', false)) {
  // ...
}

if (client.getStringValue('some-string-flag', 'qux')) {
  // ...
}

if (client.getNumberValue('some-numeric-flag', 9))) {
  // ...
}
```

The following information gets displayed in DataDog:

![image](https://github.com/thomaspoignant/go-feature-flag/assets/785542/30398160-09f7-4893-a3d1-5a831bf1c935)

Is that sufficient?
