### ISSUE TITLE
(change) Percentage - accept fractional affectation

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2031]
### Requirements

As of today when configuring a flag with a percentage affection rule should have a total affectation to 100.

If it is not the case the rule may miss behave because we expect the total of the percentage to be 100.

In this example the flag is not considered as **valid**.

```yaml
test-flag:
  variations:
    enabled: false
    disabled: false
  defaultRule:
    percentage:
      enabled: 10
      disabled: 100
```

To be able to forgive a bit more if a mistake is made when configuring the flag, we should move to a fractional repartition.

In this case we will affect:
- `10/110` to enabled variation
- `100/110` to disabled variation

For flag that were well configured this will not change anything so we should have no changes for already configured flags.
