### ISSUE TITLE
(feature) Specify custom field key for evaluation date time of scheduled rollout

### ISSUE THREAD

**Issue by itchyny** [thomaspoignant/go-feature-flag#2054]
### Requirements

The scheduled rollout is evaluated against the current date time ([code](https://github.com/thomaspoignant/go-feature-flag/blob/v1.30.0/internal/flag/internal_flag.go#L175)). We're planning to create a hidden feature so that QA can verify the behavior of features after (and before) the expected release date. Can we specify the field key so that we post the evaluation date for the scheduled flag to the go-feature-flag server?

**Comment by thomaspoignant** [comment]
Hello @itchyny 
I am not sure I have well understood your need.

If you want to allow a feature for your QA you can use a targeting rule to specify them.
Something like:

```yaml
my-new-feature:
  variations:
    enabled: true
    disabled: false
  targeting:
    - query: role eq "QA"
      variation: enabled
  defaultRule:
    variation: disabled
```

This will enable the feature only for the people with the role of QA in their evaluation context.
You can always have more specific rules if you prefer to work with a key.

If the activation of the feature has to be time-based, you can also modify the targeting rule at the same time.

Something like that:

```yaml
my-new-feature:
  variations:
    enabled: true
    disabled: false
  targeting:
    - name: qa_testing_rule
      query: role eq "QA"
      variation: disabled
  defaultRule:
    variation: disabled
  scheduledRollout:
    - date: 2020-04-10T00:00:00.1+02:00
      targeting:
        - name: qa_testing_rule
          query: role eq "QA"
          variation: enabled
```

Here you can see that we have named the targeting rule to be able to modify it in the `scheduledRollout`.
And as you can see here, we are modifying only the rule applying to QA.

**Comment by itchyny** [comment]
In that way, QA can verify that the feature will be released at that date time by testing just moments before and after the configured date time. Also the flag configuration needs branching by the roles, and QA cannot test that the scheduled date is properly configured for other roles.
I imagine that if we could configure the custom field key for the evaluation date time, QA can specify a hidden query parameter that will be posted to the goff server, and can make sure that the feature will surely the expected date time.

```yaml
feature-a:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: disabled
  scheduledRollout:
    - date: 2020-04-10T01:00:00Z
      dateTimeKey: now
      defaultRule:
        variation: enabled
```

```sh
 $ curl -XPOST -H Content-Type:application/json -d '{"evaluationContext":{"key":"."}}' localhost:1031/v1/feature/feature-a/eval
{"trackEvents":true,"variationType":"disabled","failed":false,"version":"","reason":"STATIC","errorCode":"","value":false,"cacheable":true}
 $ curl -XPOST -H Content-Type:application/json -d '{"evaluationContext":{"key":".","now":"2020-04-10T00:59:59Z"}}' localhost:1031/v1/feature/feature-a/eval
{"trackEvents":true,"variationType":"disabled","failed":false,"version":"","reason":"STATIC","errorCode":"","value":false,"cacheable":true}
 $ curl -XPOST -H Content-Type:application/json -d '{"evaluationContext":{"key":".","now":"2020-04-10T01:00:00Z"}}' localhost:1031/v1/feature/feature-a/eval
{"trackEvents":true,"variationType":"enabled","failed":false,"version":"","reason":"STATIC","errorCode":"","value":true,"cacheable":true}
```
