### ISSUE TITLE
(feature) Support for Custom Assignment/Targeting Keys

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2135]
## Description
_This feature was originally asked by Ricardo Tomasi in this [slack conversation](https://gophers.slack.com/archives/C029TH8KDFG/p1720704534731819)._
 
This feature request proposes to do the percentages rollout based on another field than the targeting key.
This would allow for greater flexibility in defining target audiences for feature flags, specifically facilitating scenarios where flags need to be assigned based on attributes other than the user ID.

## Current Behavior:
Currently, GO Feature Flagassign variations are based on the targetingKey by default. This presents limitations when targeting needs to be based on other attributes, like team ID.

This can cause some limitations, especially when using a client-side SDK that uses a single evaluation context to evaluate all the flags and it is not possible to change it per flags.

> [!NOTE]
> In a percentage split the way we affect users to the variation is something like 
> ```
> (targetingKey + flag name) = 100000
> 
> // depending on the percentage we have buckets like this
> | variation A (0..5000) | variation B (5000...40000) | variation C (40000...100000) |
> ``` 

## Desired Behavior:
**Dynamic Targeting Key**: Introduce a new field within the feature flag configuration to allow choosing which field from the evaluation context will be used to do the variation affectation in a percentage split of the traffic.

# Proposed solution

To support this feature we can add a new field in the rules called `bucketingKey` that will allow to specify which key from the evaluation context will be used to split the traffic.

It will look like this:

```yaml
my-flag:
  variation:
     enabled: true
     disabled: false
  defaultRule:
     percentage:
       enabled: 10
       disabled: 90
     bucketingKey: teamId
```

Now when evaluating a flag with an evaluation context looking like this:
```json
{
  "targetingKey": "04b86a91-101d-4b16-87c7-ecb3af38a869",
  "email": "contact@gofeatureflag.org"
  "teamId": 156
}
```

Instead of affecting like this :
```
(targetingKey + flag name) = 100000
```

We will do 
```
(teamId + flag name) = 100000
```

⚠️ If for any reason the you `bucketingKey` is not available in the evaluation context, we will use the `targetingKey` as a fallback method to affect the right variation.

**Comment by ricardobeat** [comment]
Hi @thomaspoignant! Thanks for taking this suggestion forward.

Would it make sense to put `bucketingKey` at the root, since it would apply to all targeting rules?

**Comment by thomaspoignant** [comment]
The problem of failing to the default is that the default may need

**Comment by thomaspoignant** [comment]
Yes, it's a great idea to put the `bucketingKey` on top level.
The problem of failing to the default is that the default may need the `bucketingKey` too.

For example in this example:
```yaml
my-flag:
  variation:
     enabled: true
     disabled: false
  defaultRule:
     percentage:
       enabled: 10
       disabled: 90
  bucketingKey: teamId
```

You can see that the `defaultRule` is percentage base, and we need a key to do the split of people.
This is why I propose to failover the `targetingKey`.

**Comment by ricardobeat** [comment]
In the same line of thought, when using `bucketingKey` I would assume `key` refers to it, and not the original `targetingKey`:

```yaml
my-flag:
  bucketingKey: teamId
  variation:
     A: false
     B: true
  targeting:
    - name: 'Teams in beta program'
      query: key in [3338, 1337]
      variation: B
  defaultRule:
     variation: A
```

**Comment by ricardobeat** [comment]
I've made a draft PR implementing this to see what it looks like. Am not sure about the naming: something like `targetingKeyFrom` / `customKey` seems more descriptive since the usual targeting key is also a bucketing key?

**Comment by thomaspoignant** [comment]
> In the same line of thought, when using `bucketingKey` I would assume `key` refers to it, and not the original `targetingKey`:
> 
> ```yaml
> my-flag:
>   bucketingKey: teamId
>   variation:
>      A: false
>      B: true
>   targeting:
>     - name: 'Teams in beta program'
>       query: key in [3338, 1337]
>       variation: B
>   defaultRule:
>      variation: A
> ```

I would avoid to use `key` for the new bucketing key.
It is more explicit to use in your targeting rules the name of the actual key than any alias.

I found it easier to understand to have something like this:

```yaml
my-flag:
  bucketingKey: teamId
  variation:
     A: false
     B: true
  targeting:
    - name: 'Teams in beta program'
      query: teamId in [3338, 1337] # <-- more explicit to use the actual key from the context (and the split will still happen based on teamId)
      variation: B
  defaultRule:
     variation: A
```


> I'm not sure about the naming: something like targetingKeyFrom / customKey seems more descriptive since the usual targeting key is also a bucketing key?

I kinda like `bucketingKey` because this is what it is.
In the documentation, we can explain it by saying something like 
```
bucketingKey is the name of the field used to split the traffic in your percentage-based rules.
If not set we are using by default the targetingKey.
```
