### ISSUE TITLE
(feature) [HELM] Allow for creating Role/RoleBinding for loading flags from ConfigMap

### ISSUE THREAD

**Issue by yafanasiev** [thomaspoignant/go-feature-flag#2196]
### Requirements

Hi! First of all, thanks for a great project!

We are setting up go-feature-flag to load flag definitions from Kubernetes ConfigMap (relay-proxy itself is deployed in Kubernetes as well) and to make it work we have to add Role and RoleBinding to ServiceAccount created by chart (which is kind of expected as well), however might be not as convenient since you can't have Helm managing all the required resources.

Would you be open to adding those RBAC resources to the chart? Or at least a generic template allowing to pass any YAML to be rendered into resource. I would be happy to do a PR for this.

Just for reference, this is how sample RBAC setup looks like:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: feature-flags-relay-proxy
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: feature-flags-relay-proxy
subjects:
- kind: ServiceAccount
  name: feature-flags-relay-proxy
roleRef:
  kind: Role
  name: feature-flags-relay-proxy
  apiGroup: ""
 ```
