### ISSUE TITLE
(feature) Detect undefined variations with the linter

### ISSUE THREAD

**Issue by kna** [thomaspoignant/go-feature-flag#2562]
### Requirements

A flag file might contain undefined variants due to a mistake.
I think it is better for the linter to report it as an error.

### Example

The following flag file is incorrect because it uses an undefined variation(`NOT_IN_VARIATIONS`).

```
# flag.goff.yaml
flag_a:
  variations:
    A: true
    B: false
  defaultRule:
    variation: NOT_IN_VARIATIONS
```

But the linter does not report an error.
```
$ docker run --rm \
  -v ./flag.goff.yaml:/flag.goff.yaml \
  gofeatureflag/go-feature-flag-lint:v1.36.1 \
  --input-format=yaml \
  --input-file=/flag.goff.yaml
(no output)
```
