### ISSUE TITLE
(feature) Adding simpler format

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#295]
### Requirements

Following the idea of @urso on this discussion #229 it could be great to add a simpler format to have an easy way to configure some flags.

The first proposal are:

#### Always true
```yaml
dev-flag:
  value: true  # can be an integer as well
```

#### A/B testing
```yaml
new-feature:
  a/b-test:   # boolean flag that returns true for 60% of our users
    percentage: 60
```

_These are examples, we may propose something different if needed_.
