### ISSUE TITLE
(bug) Kafka exporter config via yaml or env

### ISSUE THREAD

**Issue by laurynas** [thomaspoignant/go-feature-flag#3207]
### Your question

Is there any way to pass kafka exporter config via `goff-proxy.yaml`?
I need to pass SASL configuration and it [looks like it should be possible](https://gofeatureflag.org/docs/integrations/export-evaluation-data/kafka#configure-the-relay-proxy) to specify it via `kafka.config` key passing Sarama configuration.

But if I try to speficy anything under `kafka.config`, I get a [Sarama producer error](https://github.com/IBM/sarama/blob/main/sync_producer.go#L108):
```
error while exporting data: writer: producer: kafka: invalid configuration 
(Producer.Return.Errors must be true to be used in a SyncProducer)
```

What would be the correct way to specify SASL configuration (via ENV keys or yaml)?

**Comment by thomaspoignant** [comment]
I am sorry I have a very limited time in the next few days, but I will look at it as soon as possible.
Can you please share with me what you've tried so I can try to reproduce as soon as possible.

**Comment by laurynas** [comment]
Hi Thomas, really appreciate you looking into this!

I tried various combinations.

### Working examples (without SASL)

With env configuration
```
RETRIEVER_KIND: http
RETRIEVER_URL: http://localhost:3001/config/gff/something
EXPORTER_KIND: kafka
EXPORTER_KAFKA_TOPIC: svc-goff.evaluation
EXPORTER_KAFKA_ADDRESSES: kafka:9092
```
With `goff-proxy.yaml`
```
retriever:
  kind: http
  url: http://localhost:3001/config/gff/something
exporter:
  kind: kafka
  kafka:
    topic: svc-goff.evaluation
    addresses: [kafka:9092]
```

### Failing examples

`error while exporting data: writer: producer: kafka: invalid configuration`

With env configuration
```
RETRIEVER_KIND: http
RETRIEVER_URL: http://localhost:3001/config/gff/something
EXPORTER_KIND: kafka
EXPORTER_KAFKA_TOPIC: svc-goff.evaluation
EXPORTER_KAFKA_ADDRESSES: kafka:9092
EXPORTER_KAFKA_CONFIG_NET_SASL_ENABLE: true
EXPORTER_KAFKA_CONFIG_NET_SASL_MECHANISMS: SCRAM-SHA-512
EXPORTER_KAFKA_CONFIG_NET_SASL_USER: TODO
EXPORTER_KAFKA_CONFIG_NET_SASL_PASSWORD: TODO
```

With `goff-proxy.yaml`
```yaml
retriever:
  kind: http
  url: http://localhost:3001/config/gff/something
exporter:
  kind: kafka
  kafka:
    topic: svc-goff.evaluation
    addresses: [kafka:9092]
    config:
      net.sasl.enable: true
      net.sasl.mechanism: SCRAM-SHA-512
      net.sasl.user: TODO
      net.sasl.password: TODO
```

```yaml
retriever:
  kind: http
  url: http://localhost:3001/config/gff/something
exporter:
  kind: kafka
  kafka:
    topic: svc-goff.evaluation
    addresses: [kafka:9092]
    config:
      Net:
        SASL:
          Enable: true
          Mechanism: SCRAM-SHA-512
          User: TODO
          Password: TODO
```

Just a few examples I tried.

### Separate issue - multiple brokers via env

Also noticed, that if I pass a list of comma separated brokers via env, I get an error:
`error while exporting data: writer: producer: kafka: client has run out of available brokers to talk to: dial tcp: address kafka:9092,kafka:9093: too many colons in address`

ENV example:
```
RETRIEVER_KIND: http
RETRIEVER_URL: http://localhost:3001/config/gff/something
EXPORTER_KIND: kafka
EXPORTER_KAFKA_TOPIC: svc-goff.evaluation
EXPORTER_KAFKA_ADDRESSES: kafka:9092,kafka:9093
```

**Comment by thomaspoignant** [comment]
I have tried with this configuration that you've provided
```yaml
retriever:
  kind: http
  url: http://localhost:3001/config/gff/something
exporter:
  kind: kafka
  kafka:
    topic: svc-goff.evaluation
    addresses: [kafka:9092]
    config:
      Net:
        SASL:
          Enable: true
          Mechanism: SCRAM-SHA-512
          User: TODO
          Password: TODO
```

and when I put a break point on the exporter inside the relay proxy I can see that the exporter has the right configuration.

<img width="810" alt="Image" src="https://github.com/user-attachments/assets/bfd06b3a-6ae8-4804-abb5-8b9d3e11fac6" />

Are you sure that the configuration you are providing works well with your Kafka Cluster?

**Comment by laurynas** [comment]
Thanks, it is very helpful! Good to know that SASL configuration can be set via yaml.

I think the problem is that when `kafka.config` is specified in yaml, the Sarama defaults are not loaded as `sarama.NewConfig()` is not executed:
https://github.com/thomaspoignant/go-feature-flag/blob/v1.42.0/exporter/kafkaexporter/exporter.go#L85
In your debug screenshot is visible that following timeout defaults were not set:
https://github.com/IBM/sarama/blob/v1.45.1/config.go#L527C2-L530C39

It would be great if yaml `kafka.config` would only override the defaults, because otherwise all defaults would need to be configured, which is quite a lot:
https://github.com/IBM/sarama/blob/v1.45.1/config.go#L523

Also there is a configuration validation function which probably would be helpful to execute when `kafka.config` is used:
https://github.com/IBM/sarama/blob/v1.45.1/config.go#L585

**Comment by thomaspoignant** [comment]
Oh good catch.
I will check that when I am back from vacation and open a PR.

**Comment by thomaspoignant** [comment]
Hey @laurynas I have open a PR for this https://github.com/thomaspoignant/go-feature-flag/issues/3207
I still need to work a bit on the tests but if you want to have a look please check it.

**Comment by laurynas** [comment]
@thomaspoignant thanks, nice and simple fix. I have tested and now defaults override seems to work fine.

But I faced another problem when specifying SASL configuration like this:
```yaml
retriever:
  kind: http
  url: http://localhost:3001/config/gff/svc-payments
exporter:
  kind: kafka
  kafka:
    topic: svc-goff.evaluation
    addresses: [localhost:9092]
    config:
      Net:
        SASL:
          Enable: true
          Mechanism: SCRAM-SHA-512
          User: TODO
          Password: TODO
```

I get a producer error:
> {"level":"error","ts":1742474248.886015,"msg":"error while exporting data: writer: invalid configuration: kafka: invalid configuration (A SCRAMClientGeneratorFunc function must be provided to Net.SASL.SCRAMClientGeneratorFunc)"}

Apparently Sarama configuration is quite strange - when using SASL it [requires to specify SCRAM client generator function](https://github.com/IBM/sarama/blob/v1.45.1/config.go#L669), but I'm not sure it is possible to do it via yaml..

Probably in this case some more logic would be needed in the exporter setup. Looking at [this example](https://github.com/IBM/sarama/blob/main/examples/sasl_scram_client/main.go#L96), maybe it could be something like this:
```go
		if c.Kafka.Config != nil {
			defaultConfig := sarama.NewConfig()
			err := mergo.Merge(c.Kafka.Config, defaultConfig)
			if err != nil {
				return nil, err
			}
			switch c.Kafka.Config.Net.SASL.Mechanism {
			case sarama.SASLTypeSCRAMSHA256:
				c.Kafka.Net.SASL.SCRAMClientGeneratorFunc = func() sarama.SCRAMClient { return &XDGSCRAMClient{HashGeneratorFcn: SHA256} }
			case sarama.SASLTypeSCRAMSHA512:
				c.Kafka.Net.SASL.SCRAMClientGeneratorFunc = func() sarama.SCRAMClient { return &XDGSCRAMClient{HashGeneratorFcn: SHA512} }
			}
		}
		return &kafkaexporter.Exporter{
			Format:   format,
			Settings: c.Kafka,
		}, nil
```
Looks quite dirty, but I don't have a better idea..
