### ISSUE TITLE
(bug) OTEL configuration is not working

### ISSUE THREAD

**Issue by tomflenner** [thomaspoignant/go-feature-flag#3228]
### Observed behaviour

Hello 👋🏻 !

We are trying to use OTEL exporter configuration as mentioned in the documentation with OpenFeature & the .NET SDK :

https://gofeatureflag.org/docs/relay-proxy/observability?_highlight=otel#tracing

```
retriever:
  kind: http
  url: XXXX
fileFormat: JSON
pollingInterval: 1.8e+06
startWithRetrieverError: true
otel:
  exporter:
    otlp:
      endpoint: "XXXX"
debug: true
openTelemetryOtlpEndpoint: "XXXX"
```

(we tried both `otel.exporter.otlp.endpoint` and `openTelemetryOtlpEndpoint`)

and also by passing env variable to the relayproxy :

```
  OTEL_EXPORTER_OTLP_COMPRESSION: "gzip"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "XXXX"
  OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "grpc"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_SERVICE_NAME: "relayproxy"
  OTEL_TRACES_EXPORTER: "otlp"
```

but we are not seeing any trace related to the relayproxy in our tool.

Is this a bug, a misconfiguration or anything else ?

Thank you in advance ! 🙏🏻 

### Expected Behavior

Seeing a relayproxy span after an evaluation from the .NET SDK

**Comment by tomflenner** [comment]
@thomaspoignant 👋🏻,

thanks for your time investigating this.

We are using autoinstrumentation in our .NET app codebase that call the relayproxy and it seems that it works for others components we have. A lot of span regarding Dapr, SQL are here.

Is there anything wrong in the .NET SDK that can prevent TraceId to be passed across the HTTP call between the app and the relayproxy ?

Do you have any idea regarding the configuration of OTLP server that can make this wont work ?

**Comment by thomaspoignant** [comment]
On my side the OTLP configuration is really basic.

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"

processors:
  batch:

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "xxx"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
```

I am not sure if the auto instrumentation works well to propagate the traces from your app to the relay proxy, but I am still curious that you have 0 traces in your tool 🤔.
