### ISSUE TITLE
(bug) Any Kafka exporter configuration causes "client has run out of available brokers to talk to" error

### ISSUE THREAD

**Issue by laurynas** [thomaspoignant/go-feature-flag#3307]
### Observed behaviour

It is follow up on https://github.com/thomaspoignant/go-feature-flag/issues/3207 issue.

Adding any kafka exporter `config` to yaml file or env, which triggers `merge.Merge`, causes producer error:
```json
{"level":"error","ts":1744441408.469124,"msg":"error while exporting data: writer: producer: kafka: client has run out of available brokers to talk to"}
```

### Expected Behavior

Exporter config overrides default sarama kafka config.

### Steps to reproduce

I did some testing - while in the golang debugger configuration looks ok and values are merged with defaults, the actual producer configuration doesn't work :( 

Working configuration:
```yaml
retriever:
  kind: http
  url: http://localhost:3001/
exporter:
  kind: kafka
  kafka:
    topic: test-evaluation
    addresses: [localhost:9092]
```

Failing configuration example:
```yaml
retriever:
  kind: http
  url: http://localhost:3001/
exporter:
  kind: kafka
  kafka:
    topic: test-evaluation
    addresses: [localhost:9092]
    config:
      Producer:
        Return:
          Successes: true
```

This configuration example just sets producer config value to return successes. It should be identical with first one, because when `config` is not provided, this property is [enabled in the exporter code](https://github.com/thomaspoignant/go-feature-flag/blob/48aa781/exporter/kafkaexporter/exporter.go#L91).

I couldn't figure out what exactly causes failure. Maybe `mergo.Merge` interferes with complex sarama configuration, maybe pointers? I guess it is quite tricky when part of configuration contains lambdas..
