### ISSUE TITLE
(bug) /goff/flags.goff.yaml not found in container after success startup

### ISSUE THREAD

**Issue by bingbeann** [thomaspoignant/go-feature-flag#3447]
### Observed behaviour

Started fine but as I updated the file on my local machine, error while updating cache will appear, timing is inconsistent, sometimes it's a 1 try away from happening, sometimes a few tries before happened.

### Expected Behavior

Should not have error to update cache after updated flags file

### Steps to reproduce

Files:
`./goff/flags.goff.yaml`
```yaml
feature-a:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: disabled
```

`./goff/goff-proxy.yaml`
```yaml
pollingInterval: 1000
retrievers:
  - kind: file
    path: /goff/flags.goff.yaml
```

Startup:
```bash
podman run --platform linux/amd64 -v "$(pwd)/goff:/goff" -p 1031:1031 gofeatureflag/go-feature-flag:latest
```

Output:
```bash
█▀▀ █▀█   █▀▀ █▀▀ ▄▀█ ▀█▀ █ █ █▀█ █▀▀   █▀▀ █   ▄▀█ █▀▀
█▄█ █▄█   █▀  ██▄ █▀█  █  █▄█ █▀▄ ██▄   █▀  █▄▄ █▀█ █▄█

     █▀█ █▀▀ █   ▄▀█ █▄█   █▀█ █▀█ █▀█ ▀▄▀ █▄█
     █▀▄ ██▄ █▄▄ █▀█  █    █▀▀ █▀▄ █▄█ █ █  █ 

GO Feature Flag Relay Proxy - Version 1.44.0
_____________________________________________
{"level":"info","ts":1747976246.7182949,"msg":"flag added","key":"bizloan_review_credit"}
{"level":"info","ts":1747976246.7222428,"caller":"api/server.go:142","msg":"Starting go-feature-flag relay proxy ...","address":"0.0.0.0:1031","version":"1.44.0"}
{"level":"info","ts":1747977227.371216,"msg":"flag updated","key":"bizloan_review_credit"}
{"level":"info","ts":1747977237.3698266,"msg":"flag updated","key":"bizloan_review_credit"}
{"level":"error","ts":1747977241.3630886,"msg":"Error while updating the cache.","error":{"error":"open /goff/flags.goff.yaml: no such file or directory","kind":"*fs.PathError","stack":null}}
{"level":"info","ts":1747977242.3711104,"msg":"flag updated","key":"bizloan_review_credit"}
```

Machine:
Macbook Pro 16-inch (November 2024), MacOS v15.4.1

Podman version:
podman version 5.4.2
