### ISSUE TITLE
(change) Provide a way to configure retriever.githubToken in k8s securely

### ISSUE THREAD

**Issue by Yaroslav-Kovalchyk-Imprivata** [thomaspoignant/go-feature-flag#594]
### Motivation

There is no way to define GitHub token securely in case relay-proxy is deployed in k8s via helm chart. 
Below is a sample of the way how githubToken is currently configured. It is required to be defined as simple text, which is not secure.

```
relayproxy:
  config: | # This is a configuration example for the relay-proxy
    listen: 1031
    pollingInterval: 1000
    startWithRetrieverError: false
    retriever:
      kind: github
      repositorySlug: "imprivata-cloud/spring-helm-gofeatureflag-poc"
      path: "goff/feature_control_config.yaml"
      branch: "VT-1906"
      githubToken: "your_secure_token"
    exporter:
      kind: log

image:
  tag: "v1.5.1"
```

### Requirements

Acceptable way to define githubToken is a k8s secret. Please provide such a capability, otherwise relay-proxy with GitHub flags configuration can't be used in real production securely.
