### ISSUE TITLE
Environment property I found the client configuration and how this is defined in the YAML rules? 

### ISSUE THREAD

**Issue by RuairiSpain** [thomaspoignant/go-feature-flag#675]
### Change in the documentation

Hi Thomas, I great work on this project. I'd like to use it in Wikipedia for the rollout of api features and have been experimenting with your project. I will probably use it but need a bit of guidance. 

I'd like to use different feature flags depending if our service is running in DEV, UAT or Prod.

Any guidance is appreciated :) 
Ruairi

In the [Docs](https://gofeatureflag.org/docs/go_module/configuration) , it's mentioned that the Environment property can be set for the client.  The link below uses a rule: property that is not used into orger YAML examples.

Current Docs:
Environment	(optional)
The environment the app is running under, can be checked in feature flag rules.
Default: ""
Check ["environments" section](https://gofeatureflag.org/docs/configure_flag/flag_format#environments) to understand how to use this parameter.

But the section:
https://gofeatureflag.org/docs/configure_flag/rule_format#environments

It uses a 'rule' property, please should this be the 'query'  property?

So I'm guessing the complete YAML should look something like:
`
dev-stg-flag:
  variations:
    enabled: true
    disabled: false
  version: "7"
  targeting:
    - name: Environment config for ffclient.Init
      query: "env == 'dev' or env == 'staging' "
      variation: enabled
  defaultRule:
    variation: disabled
`

**Comment by thomaspoignant** [comment]
Hello @RuairiSpain this is exactly how you should use it.

The way I am using it is something like this:
```yaml
test-flag:
  variations:
    A: "A"
    B: "B"
    C: "C"
  targeting:
    - query: env eq "pre"
      variation: A
    - query: env eq "pro"
      variation: B
  defaultRule:
    variation: C
```

The documentation is not super clear here, I will improve the documentation to make it more explicit.
