### ISSUE TITLE
(bug) <title> Environment rule not working

### ISSUE THREAD

**Issue by agufagit** [thomaspoignant/go-feature-flag#697]
### Observed behavior

configuration file:

```yaml
feature:
  variations: # All possible return value for your feature flag
    A: false
    B: true
  targeting: # If you want to target a subset of your users in particular
    - query: env == "development"
      variation: A
    - query: (env == "production") or (env == "staging") or (env == "qa")
      variation: B
  defaultRule: # When no targeting match we use the defaultRule
    variation: B
```

golang:
```go
err := ffclient.Init(ffclient.Config{
  Environment: "development",
  Context:     context.Background(),
  Retriever: &fileretriever.Retriever{
	Path: "./flags.yaml",
  },
})
if err != nil {
  log.Fatalf("Failed to init feature flag: %v", err)
}
flag_feature, _ := ffclient.BoolVariation("feature", ffuser.NewAnonymousUser("1"), true)
println(flag_feature)
```

defaultRule variation `true` is returned

### Expected Behavior

Expect `false` returned

### Steps to reproduce

I walked through code, it looks like "env" field is not set automatically in newly created user object.

the code in `variation.go` line 407
```go
flagValue, resolutionDetails := f.Value(flagKey, user,
		flag.EvaluationContext{Environment: g.config.Environment, DefaultSdkValue: sdkDefaultValue})
```

that `user` object is passed through until `internal/flag/rule.go` line 47
```go
parser.Evaluate(r.GetQuery(), utils.UserToMap(user))
```

and I'm not seeing any code that sets `env` field
